# Generated by Django 4.1.7 on 2023-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='Perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ig_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='website_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
