# Generated by Django 4.1.7 on 2023-04-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo del post', max_length=50)),
                ('subtitulo', models.CharField(help_text='Subtitulo', max_length=100)),
                ('cuerpo', models.TextField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('ultima_mod', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
