# Generated by Django 4.1.7 on 2023-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(default='Sin Categoria', max_length=75),
        ),
    ]
