# Generated by Django 4.1.7 on 2023-04-17 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default='SinCategoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.categoria'),
        ),
    ]
