# Generated by Django 4.1.7 on 2023-04-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_categoria_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Resumen del post. . .', max_length=250),
        ),
    ]
