# Generated by Django 4.1.7 on 2023-04-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='.\\posts-img/'),
        ),
    ]
