# Generated by Django 4.1.7 on 2023-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_header_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts-img/'),
        ),
    ]
